format = """
[](#b37f00)\
[󰣇 ](bg:#b37f00 fg:#1a1200)\
[](bg:#e6a300 fg:#b37f00)\
$username\
[](bg:#ffbc1a fg:#e6a300)\
$directory\
[](bg:#ffcb4d fg:#ffbc1a)\
$git_branch\
$git_status\
[](bg:#ffda80 fg:#ffcb4d)\
$c\
$golang\
$nodejs\
$rust\
$python\
[](fg:#ffda80 bg:#ffe9b3)\
$docker_context\
[](fg:#ffe9b3 bg:#1a1200)\
$time\
[ ](#1a1200)\
\n[](#ffb500) 
"""

command_timeout = 5000

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#e6a300 fg:#1a1200"
format = '[ $user ]($style)'

[directory]
style = "bg:#ffbc1a fg:#1a1200"
format = "[ $path ]($style)"
read_only = " "
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
[directory.substitutions]
"media" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Images" = " "

[c]
symbol = " "
style = "bg:#ffda80 fg:#1a1200"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#ffe9b3 fg:#1a1200"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#ffcb4d fg:#1a1200"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ffcb4d fg:#1a1200"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#ffda80 fg:#1a1200"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#ffda80 fg:#1a1200"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#ffda80 fg:#1a1200"
format = '[ $symbol $version(\($virtualenv\)) ]($style)'

[rust]
symbol = ""
style = "bg:#ffda80 fg:#1a1200"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
style = "bg:#1a1200"
format = '[ 󱑍 $symbol$time ]($style)'
